version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      microsoft-extensions:
        patterns:
          - "Microsoft.Extensions.*"
      xunit:
        patterns:
          - "xunit*"
          - "Microsoft.NET.Test.Sdk"
          - "coverlet.*"
      serilog:
        patterns:
          - "Serilog*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
