name: Test and Publish

on:
  push:
      branches:
        - mane
  pull_request:
      branches:
        - mane
  release:
    types:
      - created

env:
  DOTNET_VERSION: '7.0.x' # The .NET SDK version to use

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            Cloudy-Canvas/bin
            Cloudy-Canvas/obj
            Cloudy-Canvas.Tests/bin
            Cloudy-Canvas.Tests/obj
          key: dotnet-dep-builds
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
