name: Nix Flake Check

on:
  push:
    branches: [ mane ]
  pull_request:
    branches: [ mane ]

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: DeterminateSystems/nix-installer-action@v23
      - uses: cachix/cachix-action@v17
        with:
          name: nix-community
          skipPush: true
      - uses: DeterminateSystems/magic-nix-cache-action@v15
      - name: Verify Flake Build
        run: |
          nix flake check \
            --option auto-optimise-store true \
            --option keep-build-log false \
            --option keep-derivations false \
            --option min-free 1073741824
      - name: Flake Build
        run: nix build .#cloudy-canvas